# enable / disable OpenCV -- THIS OPTION EFFACTS MARVIN ONLY
  USE_OPENCV = 1
# USE_OPENCV = 0

# use internal / external caffe
  USE_EXTERNAL_CAFFE = 0
# USE_EXTERNAL_CAFFE = 1

# uncomment and modify EXTERNAL_CAFFE_ROOT if you know what are you doing
# EXTERNAL_CAFFE_ROOT = $(HOME)/caffe

CUDA_ROOT   = /usr/local/cuda-8.0
CUDNN_ROOT  = /usr/local/cuda-8.0
MATLAB_ROOT = /usr/local/MATLAB/R2016b

# CUDA Architecture
CUDA_GENCODE :=arch=compute_52,code=sm_52

# BUILD JOBS
CAFFE_BUILD_JOBS = 12

# Marvin DATATYPE, see marvin.hpp
MARVIN_DATATYPE = 1

# enable / disable pkg-config for OpenCV lookup
  USE_PKGCONFIG = 0
# USE_PKGCONFIG = 1